### PR TITLE
 Add spral linear solver on Linux 

### PR DESCRIPTION
**Pull request by traversaro**
This PR enables support for the spral linear solver (see https://coin-or.github.io/Ipopt/INSTALL.html#DOWNLOAD_SPRAL) on Linux, as for now spral on conda-forge is available just on Linux.

Beside modifications to enable the compilation and the tests, this PR also backports https://github.com/coin-or/Ipopt/pull/677 to the feedstock, to ensure that mumps remain the default linear solver, has anyhow that will be the case in the next release of ipopt.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
This will fail on arm and ppc, let's see if we can fix that with https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4802 .

**Comment by traversaro** [comment]
@conda-forge/ipopt the PR is ready for review, thanks!

**Comment by traversaro** [comment]
@conda-forge/ipopt if there is no specific objection, I will like to merge this by the end of this week.

**Comment by bluescarni** [comment]
@traversaro sorry for not replying earlier...

If I understand correctly, for the conda package the SPRAL solver is **not** the default solver option right?

I am a bit concerned about the numerous hoops you had to go through to make the segfaults go away and the general attitude towards memory bugs as exemplified here:

https://github.com/ralna/spral/issues/67

Other than that, looking good to me.

**Comment by traversaro** [comment]
> If I understand correctly, for the conda package the SPRAL solver is **not** the default solver option right?

Exactly, this is correct. Without any specific intention, `spral` was made the default linear solver (if available) in ipopt upstream. However, this was fixed in https://github.com/coin-or/Ipopt/pull/677 and I backported this fix here. 

I explicitly make sure that by default ipopt works without any strange OMP_* env variable in the test script, where the test for the `ipopt` binary is running without setting env variable, see https://github.com/traversaro/ipopt-feedstock/blob/e79e47bbed6c7f81452b222eec147596a297bbcf/recipe/run_test.sh#L8 .

**Review by bluescarni — APPROVED** [review]

**Comment by edwardsun** [comment]
Hello, I just want to follow up on this feature.
link: https://github.com/mechmotum/cyipopt/issues/233
In short, it seems cyipopt 1.3.0 on conda does not seem to allow "spral" linear solver yet.

**Comment by traversaro** [comment]
Can you open a new issue in the feedstock reporting the mamba list of the environment in which you have the problem? Thanks!

**Comment by edwardsun** [comment]
Hi,
I'm not sure what you mean by saying "open a new issue in the feedstock".
Is it just creating a new issue in the cyipopt repo?
Thanks.

________________________________

**Comment by traversaro** [comment]
I mean open a new issue in this repo, thanks!

**Pull request merged**
