### PR TITLE
Vendor CMake build files for Windows

### PR DESCRIPTION
**Pull request by traversaro**
As discussed in https://github.com/conda-forge/ipopt-feedstock/issues/51, having the files directly in the recipe rather then in another repo simplifies maintenance. Once https://github.com/ycollet/coinor-cmake is maintained again and supports Ipopt 3.13, we can then suggest the changes that we need and switch to use it directly again. 

Files imported from https://github.com/traversaro/coinor-cmake/commit/2cabf53c332430b603af51b34122bc4d26d55ae1

Fix https://github.com/conda-forge/ipopt-feedstock/issues/51

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
The only doubt that I have is that the CMake files are licensed under LGPL-3.0-only, so we should now change the feedstock/recipe license to account for that, but I did not found any way to do that via meta.yaml, do you have any suggestion @conda-forge/ipopt ? Thanks!

**Comment by moorepants** [comment]
> The only doubt that I have is that the CMake files are licensed under LGPL-3.0-only, so we should now change the feedstock/recipe license to account for that, but I did not found any way to do that via meta.yaml, do you have any suggestion @conda-forge/ipopt ? Thanks!

I don't think there is a good canned solution for this. I do think it is safe to license every specific cmake file with LGPL, as it is standalone wrt to the rest of the feedstock.

**Comment by traversaro** [comment]
>  I do think it is safe to license every specific cmake file with LGPL, as it is standalone wrt to the rest of the feedstock.

Ok, I added a license file in the CMake directory for doing that.

**Comment by traversaro** [comment]
The PR should be now ready.

**Comment by moorepants** [comment]
LGTM

@bluescarni, @jschueller, @pstjohn any objections to this?

**Comment by traversaro** [comment]
@moorepants feel free to let me know if there is anything I can do to get this in, thanks!

**Comment by moorepants** [comment]
Just wanted to make sure others were cool with it. Let's give a couple more days and then I'll merge.

**Comment by traversaro** [comment]
> 
> 
> Just wanted to make sure others were cool with it. Let's give a couple more days and then I'll merge.

Perfect, thanks!

**Comment by moorepants** [comment]
Also, you should add yourself as a maintainer here if you haven't.

**Comment by traversaro** [comment]
> 
> 
> Also, you should add yourself as a maintainer here if you haven't.

Done in https://github.com/conda-forge/ipopt-feedstock/pull/59/commits/69c984991cb0538bb81b0f35325db329e395e00e .

**Comment by traversaro** [comment]
@moorepants friendly ping

**Comment by moorepants** [comment]
Merging!

**Comment by jschueller** [comment]
@traversaro these should be fixed once again to go up to 3.14.0

**Comment by traversaro** [comment]
> @traversaro these should be fixed once again to go up to 3.14.0

Sure, let me open an issue: https://github.com/conda-forge/ipopt-feedstock/issues/64 .

**Pull request merged**
