### PR TITLE
Attempt bump to 3.12.8.

### PR DESCRIPTION
**Pull request by bluescarni**

### CODE REVIEW

**Comment by jakirkham** [comment]
The token here is expired. Please see the ["Near term" plan]( https://github.com/conda-forge/conda-forge.github.io/issues/426#issuecomment-321897876 ) on how to fix this.

**Comment by bluescarni** [comment]
@jakirkham this is not urgent, I can close the PR and re-open it once things are settled back to normal. If I understood correctly, a PR will be automatically opened at one point to solve the token issue?

**Comment by pstjohn** [comment]
So with 434907f5350826f04dd89d20b367efd41074fcd9 we should be able to merge this now, correct?

**Comment by jakirkham** [comment]
I believe so. @isuruf?

**Comment by isuruf** [comment]
Yes, it's okay to merge now

**Comment by pstjohn** [comment]
Awesome, thanks!

**Pull request merged**
