### PR TITLE
Enable OSX ARM64 

### PR DESCRIPTION
**Pull request by jcarpent**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jcarpent** [comment]
Should wait for https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=366491&view=results

**Comment by moorepants** [comment]
Looks like there is a failure on that azure link:

`conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-arm64: {'ampl-mp', 'mumps-seq=5.2'}`

**Comment by traversaro** [comment]
> 
> 
> Looks like there is a failure on that azure link:
> 
> `conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-arm64: {'ampl-mp', 'mumps-seq=5.2'}`

Yes, a bunch of dependency are missing, see https://conda-forge.org/status/#armosxaddition for more info:
ipopt_missing_deps

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
I built all dependencies as well as ipopt (natively on a M1) and uploaded it to https://anaconda.org/tobiasrobotics/

**Comment by Tobias-Fischer** [comment]
Sure @moorepants - I realise that this solution is far from optimal. I figured that building natively is a good first step, and commented in the PRs of the dependencies what was needed to get it to work. Cross-compiling and getting the PRs merged into the feedstocks is going to be the next step, contributions are more than welcome :)

**Pull request closed without merging**
