### PR TITLE
Add MKL variant (supporting pardisomkl linear solver)

### PR DESCRIPTION
**Pull request by whophil**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This adds a Pardiso MKL build variant (in addition to the original `mumps`/`metis` build).

I followed the guidelines from the [official install instructions](https://coin-or.github.io/Ipopt/INSTALL.html#DOWNLOAD_PARDISOMKL), which state:

> If you want to compile Ipopt with the Pardiso library that is included in Intel MKL, it is sufficient to ensure that MKL is used for the linear algebra routines (Blas/Lapack), see BLAS and LAPACK.

Thus, to build the Pardiso MKL variant:
- ask for the MKL variants of `liblapack` and `libblas`
- add `mkl` as a run dependency

I adjusted the compiler flags appropriately (I think). The basic test passes on Linux. I did not do any local testing for Windows, so there may be some iterations to get that working.

Relates to #22

### CODE REVIEW

**Comment by moorepants** [comment]
It isn't clear to me if you are making this optional or not. mkl should be an optional dependency to this package, as many systems only run with openblas or other blas implementations. conda forge handles switching between blas variants as described here: https://conda-forge.org/docs/maintainer/knowledge_base.html#blas. But I'm not sure exactly how to handle this, as we don't want to force an mkl install with this package.

**Comment by moorepants** [comment]
I see now that there are two build variants. What does this look like for the user? How would they install one or the other variant?

**Comment by whophil** [comment]
> I see now that there are two build variants. What does this look like for the user? How would they install one or the other variant?

This will produce two distinct packages with different sets of dependencies.

If you don't care which one you want:
```
conda install -c conda-forge ipopt
```
I don't know which is "preferred" if you don't specify a variant.

If you want a specific variant, use a pattern match on the build string, e.g.
```
conda install -c conda-forge ipopt=*=*mumps
conda install -c conda-forge ipopt=*=*pardisomkl
```

This also works in an enviornment.yml file
```
dependencies:
  - ipopt * *pardisomkl
```

If you specify the `pardisomkl` build, this will necessarily install the `mkl` package due to the dependencies of the `pardisomkl` variant of this package.

**Comment by moorepants** [comment]
Ok, cool. Didn't know all that was possible. Thanks!

**Comment by whophil** [comment]
Me neither, until very recently!

All the builds are passing now, but I'm pretty new to the conda-forge ecosystem, so we might want to get some more eyes on this before merging.

A few questions:
1. It looks like support for Windows was dropped with `3.14.0` - was this intentional? I've updated `bld.bat` in this PR, but it's totally untested.
2. When installing the `pardisomkl` variant, the environment installs `openblas` versions of `libblas` and `liblapack`. I would have expected the `mkl` variants. Does `ipopt mytoy.nl` sufficiently test the linear solve?

**Comment by moorepants** [comment]
I think the CI will only build against the reference implementations of blas/lapack (netlib) unless you force it to do otherwise.

**Comment by moorepants** [comment]
> It looks like support for Windows was dropped with 3.14.0 - was this intentional?

It seems so from the last PR. I'm not sure why it was dropped instead of fixing it in the PR.

**Comment by moorepants** [comment]
> does ipopt mytoy.nl sufficiently test the linear solve?

You like have to set the option in IPOPT to select the solver for the test problem to use it.

**Comment by traversaro** [comment]
Thanks a lot @whophil ! I was wondering, there is any specific reason why you need to have a variant, instead of enabling both `pardisomkl` and `mumps` as part of the same build and then leaving the user to specify which linear solver to use at runtime using [`linear_solver`](https://github.com/coin-or/Ipopt/blob/9dd52bc75399bee4cc9cae45350359b29c6289e7/doc/options.dox#L1082) parameter? In the future we may want to add more linear solvers (for example spral), and having variant for each one may not be the convenient option.

**Comment by traversaro** [comment]
> 
> 
> Thanks a lot @whophil ! I was wondering, there is any specific reason why you need to have a variant, instead of enabling both `pardisomkl` and `mumps` as part of the same build and then leaving the user to specify which linear solver to use at runtime using [`linear_solver`](https://github.com/coin-or/Ipopt/blob/9dd52bc75399bee4cc9cae45350359b29c6289e7/doc/options.dox#L1082) parameter? In the future we may want to add more linear solvers (for example spral), and having variant for each one may not be the convenient option.

I read a bit more the OP, and I get it know. However, unless I am not getting something, it should be perfectly possible to build ipopt by linking mkl and still use mumps/metis? Perhaps the variant should be related to which blas/lapack version is used at compilation/link time, rather then to the enabled linear solver?

**Comment by moorepants** [comment]
If you build against mkl with the pardiso link, what will happen when you only have openblas available in your conda env?

**Comment by traversaro** [comment]
> 
> 
> If you build against mkl with the pardiso link, what will happen when you only have openblas available in your conda env?

I am not 100% sure, but I guess normal `blas`/`lapack` function will work fine, but loading the library will fail because some symbols from pardisomkl will not be found. For that I think that something like `with-mkl-runtime-dependency` and `without-mkl-runtime-dependency` make more sense/are more flexible as variants instead of `mkl` vs `mumps/metis` .

**Comment by moorepants** [comment]
It would be nice if you happen to have mkl installed, that the pardiso solver would then be available. This would allow you to switch among different blaslapack variants in your conda env and ipopt wouldn't have to be reinstalled. It does seem likely that building against mkl in the recipe here, would likely allow that to happen. But one of the conda-forge experts would have to confirm. Or we'd have to test it. Offhand I'm not sure how one would test with/without mkl in the test section of the recipe to confirm this.

**Comment by traversaro** [comment]
> It would be nice if you happen to have mkl installed, that the pardiso solver would then be available.

This seems possible with regular Pardiso, quote from https://github.com/coin-or/Ipopt/blob/ea38b885db4ba947932a3eec569d661d498f6aa0/doc/install.dox#L733 :

> Ipopt can load HSL or Pardiso libraries at runtime.

Not sure if this is possible with PardisoMKL as of Ipopt 3.14 .

**Comment by whophil** [comment]
I appreciate all the discussion! I'm new to IPOPT so my knowledge has a lot of gaps, but I'm hoping we can find a solution that makes sense.

Of the linear solvers listed in the IPOPT docs, which ones can be selected at runtime? _In an ideal world_, the conda package would support all of those, assuming the user can provide the appropriate shared lib at runtime - likely by conda install for the free solvers, or in `LD_LIBRARY_PATH` for those with license restrictions. For the conda-forge build, we will probably need to skip those which require licensed libraries _at compile time_.

@traversaro brings up a good point - variants are only needed if the different solvers have compile-time requirements that conflict. Is that true if we support Pardiso MKL? If we use the MKL variants of `lapack` and `blas` at compile-time, will that actually break something if we choose _not_ to use Pardiso MKL as the linear solver? If so, we do indeed need a `nomkl` and `mkl` variant.

The original intent of this PR was just to add support for Pardiso MKL, which is probably how I ended up with the mumps/pardiso variants, but I'm happy to rescope/refactor so that this makes sense and supports other solvers in the future.

**Comment by moorepants** [comment]
I think you have to test it to see if it works. Maybe figuring out how you can test an environment with and without mkl in this recipe would let you see if you can build against mkl and then test against openblas.

**Comment by moorepants** [comment]
Maybe this downstream tests could let you switch blas variants: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#downstream-tests

**Comment by moorepants** [comment]
As a first try you can build this package as you have it now, locally. Then create a new environment with the mkl variant. Switch the blas implementation with https://conda-forge.org/docs/maintainer/knowledge_base.html#switching-blas-implementation and see if ipopt still runs if the linear solver is set to mumps.

**Comment by whophil** [comment]
> Maybe this downstream tests could let you switch blas variants: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#downstream-tests

I believe specifying a `downstream` will run the tests of the downstream package, with the current package installed. So I suppose that would mean that we need to create a package which can run the `ipopt` tests (i.e., it needs to have `ipopt` sources) but also requires MKL. Am I thinking about this correctly?

On the conda-forge gitter, the recommendation at the moment is to update conda-build to support test variants... See discussion around https://gitter.im/conda-forge/conda-forge.github.io?at=60d2aa996c992105fd94a412

**Comment by moorepants** [comment]
Yes, it does seem that test variants are needed in the meta.yaml file and it doesn't seem to have support for that.

**Comment by moorepants** [comment]
I thought the downstream thing could be used to fake a test variant.

**Comment by moorepants** [comment]
If you can figure out how to test it locally and confirm it is working, that would be sufficient for me.

**Comment by whophil** [comment]
Here's my train of thought. Does this make sense to you?
- Support for the Pardiso MKL linear solver requires `mkl` libs to be available at compile time.
- If `mkl` is available at compile time, then the `ipopt` shared lib links to `mkl` shared libs. So if `mkl` is available at compile time, `mkl` needs to be available at run time.
- We still wish to have a version of `ipopt` which does not require `mkl`.
- Therefore, a MKL variant of `ipopt` is required to have Pardiso MKL.

I've updated the recipe so it now builds `nomkl` and `mkl` variants.
- The mumps linear solver is supported (and tested) in both variants.
- The Pardiso MKL linear solver is tested in only the `mkl` variant.

It should be easy to add more linear solvers (like spral) later on, if the solver libraries can be made available at both compile and run-time.

I think this is ready for review again. I do want to point out that Windows is still excluded (and the changes to bld.bat are thus untested). We can bring Windows support back in a separate PR, if desired.

**Comment by moorepants** [comment]
> So if mkl is available at compile time, mkl needs to be available at run time.

I'm not sure that is true. I don't think dynamically linking against a certain version of blas/lapack at compile time means you can't swap it out with another at run time. The only thing I'm not sure of is if compiling against mkl blas/lapack + paradiso somehow prevents the hotswapping at runtime.

I recommend compiling ipopt aginst mkl+paradiso locally, then switching to openblas for run time and see if it throws any errors when running an example. If that works, we only need 1 variant.

**Comment by moorepants** [comment]
Reading here: https://conda-forge.org/docs/maintainer/knowledge_base.html#blas

It looks like you can get a matrix of blas builds with:

```
requirements:
  host:
    - {{ blas_impl }}
  run:
    - libblas * *{{ blas_impl }}
    - {{ blas_impl }}
 ```

You currently have a specific build for mkl it seems:

```
requirements:
  host:
    - mkl
  run:
    - libblas * *mkl
    - mkl
```

If you do the latter, then just check locally if the build works with openblas by creating an environment with your build and switching:

```
conda install "libblas=*=*openblas"
```

**Comment by whophil** [comment]
> I don't think dynamically linking against a certain version of blas/lapack at compile time means you can't swap it out with another at run time. The only thing I'm not sure of is if compiling against mkl blas/lapack + paradiso somehow prevents the hotswapping at runtime.
> 
> I recommend compiling ipopt aginst mkl+paradiso locally, then switching to openblas for run time and see if it throws any errors when running an example. If that works, we only need 1 variant.

It is possible to install the `mkl` variant of `ipopt` alongside `libblas * *openblas`. In this environment, `ipopt` runs using both mumps and pardisomkl linear solvers. 

However this environment still requires `mkl`! When `mkl` libs are available during compile, the ipopt `configure` process finds the Pardiso MKL solver and links to some MKL libs directly. The `ldd` output below shows this - the `libipopt.so` used here is generated by the `3.14.0-mkl` variant at f2da24cdd41f34bdf4ad2bb1ae53a426774e399f

```
(base) phil@phil-p1:~/Desktop$ ldd libipopt.so
	linux-vdso.so.1 (0x00007ffc187b9000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f25d6773000)
	libdmumps_seq-5.2.1.so => not found
	libmumps_common_seq-5.2.1.so => not found
	libpord_seq-5.2.1.so => not found
	libmpiseq_seq-5.2.1.so => not found
	libesmumps-6.so => not found
	libscotch-6.so => not found
	libscotcherr-6.so => not found
	libmetis.so => not found
	libgfortran.so.5 => /lib/x86_64-linux-gnu/libgfortran.so.5 (0x00007f25d64a9000)
	libmkl_intel_lp64.so.1 => not found
	libmkl_sequential.so.1 => not found
	libmkl_core.so.1 => not found
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f25d64a1000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f25d62bf000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f25d6170000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f25d5f7e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f25d6a19000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f25d5f61000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f25d5f3e000)
	libquadmath.so.0 => /lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f25d5ef4000)
```

If I understand correctly, we need to maintain a version of `ipopt` which doesn't require MKL to run. Therefore, I still think we need the variant.

**Comment by moorepants** [comment]
I see that you can install variants like this:

```
conda install -c conda-forge ipopt=*=*mkl
conda install -c conda-forge ipopt=*=*nomkl
```

What will happen when you do:

```
conda install -c conda-forge ipopt
```

?

**Comment by whophil** [comment]
I am not able to find anything explicitly documenting the behavior, but I would guess standard conda rules apply - you will get the latest version that is compatible with your environment.

In the case that your supports both `nomkl` and `mkl` variants, I don't know if the behavior is defined.

On my local machine I get `nomkl` but that could be totally chance.
```
(cf) phil@phil-p1:~/repos/ipopt-feedstock$ conda create --prefix=./deleteme -c file://$(pwd)/build_artifacts -c conda-forge --override-channels ipopt
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.1
  latest version: 4.10.2

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /home/phil/repos/ipopt-feedstock/deleteme

  added / updated specs:
    - ipopt


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ipopt-3.14.0               |            nomkl         1.2 MB  file:///home/phil/repos/ipopt-feedstock/build_artifacts
    ------------------------------------------------------------
                                           Total:         1.2 MB

```

**Comment by traversaro** [comment]
> In the case that your supports both `nomkl` and `mkl` variants, I don't know if the behavior is defined.

I do not know which one is the higher priority as it is, but I think in this case you can use something called "track_feature" to decide which one has the higher priority, I never used it but I learned about them in a recent comment by @wolfv  in https://github.com/mamba-org/mamba/issues/986#issuecomment-855836169, looking on google I was able to find some docs in https://github.com/mamba-org/mamba/issues/986#issuecomment-855836169 but I do not know anything more on this.

**Comment by moorepants** [comment]
I'm good with this PR as it stands. If you want to add the track features, that's fine by me too. Thanks @whophil !

**Comment by wolfv** [comment]
Hey, thanks @traversaro for the pin.

Speaking for "mamba" I'd recommend to either have a track_feature on the non-default variant itself, or to make sure to have a "first-level" dependency that has a track feature.

I've written down how mamba is handling this: https://mamba.readthedocs.io/en/latest/advanced_usage/package_resolution.html

The best docs for conda are probably here (under "Running the solver") https://www.anaconda.com/blog/understanding-and-improving-condas-performance

**Comment by whophil** [comment]
Thanks @wolfv for the references!

For this project - if we were to use `track_features` to weigh down one variant, should it be the `mkl` or `nomkl` version, and why?

If we prefer the `mkl` variant, then the user will be able to use Pardiso MKL linear solver if their environment/system supports it.
If we prefer the `nomkl` variant, then the user will need to explicitly specify `ipopt * *mkl` in order use the Pardiso MKL solver.

**Comment by moorepants** [comment]
I don't know if it is possible, but if MKL is installed in the environment it should install the ipopt mkl variant, otherwise not.

If you make the preference MKL with track features, will it work like that?

> If we prefer the mkl variant, then the user will be able to use Pardiso MKL linear solver if their environment/system supports it.

That statement sounds like it will work like that.

**Comment by whophil** [comment]
Update: Windows w/ MKL is giving me some issues. And it seems like the CMake files have some syntax errors when `PARDISO_MKL=1`. If anybody has experience building Windows w/ MKL please feel free to chime in.

**Comment by traversaro** [comment]
The original CMake build system we base this on was originally made for Ipopt 3.12, and we adapted it for 3.13 and 3.14 . Given that the distinction between Pardiso and Pardiso MKL was introduced (if I am not wrong) in Ipopt 3.14, probably it needs to be adapted. I can look into that during next week if you need help.

**Comment by traversaro** [comment]
This is a simple example of using track_features to de-prioritize a variant: https://github.com/conda-forge/topologytoolkit-feedstock/blob/b1184ce7e2c4be045e0a29cb4e005eee60bed453/recipe/meta.yaml#L37 .

**Comment by whophil** [comment]
Sorry @galpin , I had forgotten about this also - and looking back at the changes, I'm afraid to say I hardly remember those as well. From what I recall, this was OK pending the Window build working. If somebody can support that, we can likely get this merged. If not, I am fine closing the PR, as my needs have changed and I don't need this immediately.

**Comment by jschueller** [comment]
going stale

**Pull request closed without merging**
