### PR TITLE
Add run_exports

### PR DESCRIPTION
**Pull request by jschueller**
@conda-forge-admin please rerender

### CODE REVIEW

**Comment by jschueller** [comment]
@pstjohn @bluescarni could you merge this ?

**Comment by bluescarni** [comment]
Looks good to me. @pstjohn ?

**Comment by moorepants** [comment]
It passes, but what does this additional do? What issue does it solve?

**Comment by bluescarni** [comment]
> It passes, but what does this additional do? What issue does it solve?

As far as I have understood, ``run_exports()`` does 2 things:

- packages requiring ``ipopt`` in their ``host`` section (i.e., as a build time dependency) will automatically have ``ipopt`` added as a ``run`` dependency, without having to spell it explicitly;
- in conjunction with the pinning expression (as done in this PR), it ensures that if a package ``P`` uses ``ipopt`` version ``x.y`` at build time, then the ``run`` dependency becomes not simply ``ipopt``, but ``ipopt-x.y``. In other words, it helps ensuring that, after installing ``P``, ``ipopt`` cannot be updated to a version ABI-incompatible with the one that was used for building the ``ipopt`` package. If you don't use the pinning machinery, it may happen that a new version of ``ipopt`` is introduced in ``conda-forge``, and the ``P`` package breaks because it would need to be recompiled with the updated ``ipopt`` package.

**Comment by moorepants** [comment]
LGTM

**Pull request merged**
