### PR TITLE
add host dependency on scotch

### PR DESCRIPTION
**Pull request by minrk**
ipopt links scotch directly, meaning it should track version pins. Lacking this leads to installation with incompatible libscotch at runtime, resulting in:

```
    import cyipopt
../../../miniconda3/envs/test/lib/python3.12/site-packages/cyipopt/__init__.py:12: in <module>
    from ipopt_wrapper import *
E   ImportError: dlopen(/Users/runner/miniconda3/envs/test/lib/python3.12/site-packages/ipopt_wrapper.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace '_SCOTCH_errorPrint'
```

This is [reported](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1019109&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3) in the conda build output:

```
WARNING (ipopt,lib/libipopt.so.3.14.16): Needed DSO lib/libesmumps.so found in ['conda-forge/linux-64::libscotch==7.0.4=h2fe6a88_5']
WARNING (ipopt,lib/libipopt.so.3.14.16): .. but ['conda-forge/linux-64::libscotch==7.0.4=h2fe6a88_5'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
WARNING (ipopt,lib/libipopt.so.3.14.16): Needed DSO lib/libscotch.so.7.0.4 found in ['conda-forge/linux-64::libscotch==7.0.4=h2fe6a88_5']
WARNING (ipopt,lib/libipopt.so.3.14.16): .. but ['conda-forge/linux-64::libscotch==7.0.4=h2fe6a88_5'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
WARNING (ipopt,lib/libipopt.so.3.14.16): Needed DSO lib/libscotcherr.so found in ['conda-forge/linux-64::libscotch==7.0.4=h2fe6a88_5']
WARNING (ipopt,lib/libipopt.so.3.14.16): .. but ['conda-forge/linux-64::libscotch==7.0.4=h2fe6a88_5'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
```

Past builds will need to be patched via repodata to match whatever scotch they were built with

### CODE REVIEW

**Comment by traversaro** [comment]
Thanks!

**Review by jschueller — APPROVED** [review]

**Review by traversaro — APPROVED** [review]

**Comment by minrk** [comment]
This is the correct dependency for how ipopt is build, but I think I was a bit hasty, because I think the actual fix is to remove the linking to scotch and metis, since only mumps is used directly.

**Comment by traversaro** [comment]
It seems that there are also still warnings in the CI:

~~~
2024-09-26T07:16:15.3615297Z WARNING (ipopt,lib/libsipopt.so.3.14.16): Needed DSO lib/libesmumps.so found in ['conda-forge/linux-64::libscotch==7.0.4=h2fe6a88_5']
2024-09-26T07:16:15.3617003Z WARNING (ipopt,lib/libsipopt.so.3.14.16): .. but ['conda-forge/linux-64::libscotch==7.0.4=h2fe6a88_5'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
2024-09-26T07:16:15.3623372Z WARNING (ipopt,lib/libsipopt.so.3.14.16): Needed DSO lib/libscotch.so.7.0.4 found in ['conda-forge/linux-64::libscotch==7.0.4=h2fe6a88_5']
2024-09-26T07:16:15.3625076Z WARNING (ipopt,lib/libsipopt.so.3.14.16): .. but ['conda-forge/linux-64::libscotch==7.0.4=h2fe6a88_5'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
2024-09-26T07:16:15.3630865Z WARNING (ipopt,lib/libsipopt.so.3.14.16): Needed DSO lib/libscotcherr.so found in ['conda-forge/linux-64::libscotch==7.0.4=h2fe6a88_5']
2024-09-26T07:16:15.3632424Z WARNING (ipopt,lib/libsipopt.so.3.14.16): .. but ['conda-forge/linux-64::libscotch==7.0.4=h2fe6a88_5'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
~~~

I think everything works anyway as we have a run dependency on scotch==7.0.4 that itself depends on libscotch==7.0.4, but eventually we could also link `libscotch` directly.

**Comment by traversaro** [comment]
> It seems that there are also still warnings in the CI:
> 
> ```
> 2024-09-26T07:16:15.3615297Z WARNING (ipopt,lib/libsipopt.so.3.14.16): Needed DSO lib/libesmumps.so found in ['conda-forge/linux-64::libscotch==7.0.4=h2fe6a88_5']
> 2024-09-26T07:16:15.3617003Z WARNING (ipopt,lib/libsipopt.so.3.14.16): .. but ['conda-forge/linux-64::libscotch==7.0.4=h2fe6a88_5'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
> 2024-09-26T07:16:15.3623372Z WARNING (ipopt,lib/libsipopt.so.3.14.16): Needed DSO lib/libscotch.so.7.0.4 found in ['conda-forge/linux-64::libscotch==7.0.4=h2fe6a88_5']
> 2024-09-26T07:16:15.3625076Z WARNING (ipopt,lib/libsipopt.so.3.14.16): .. but ['conda-forge/linux-64::libscotch==7.0.4=h2fe6a88_5'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
> 2024-09-26T07:16:15.3630865Z WARNING (ipopt,lib/libsipopt.so.3.14.16): Needed DSO lib/libscotcherr.so found in ['conda-forge/linux-64::libscotch==7.0.4=h2fe6a88_5']
> 2024-09-26T07:16:15.3632424Z WARNING (ipopt,lib/libsipopt.so.3.14.16): .. but ['conda-forge/linux-64::libscotch==7.0.4=h2fe6a88_5'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
> ```
> 
> I think everything works anyway as we have a run dependency on scotch==7.0.4 that itself depends on libscotch==7.0.4, but eventually we could also link `libscotch` directly.

But this will be superseded by https://github.com/conda-forge/ipopt-feedstock/pull/112 .

**Pull request merged**
