### PR TITLE
Fix problem in Ipopt::IsFiniteNumber and Windows library name

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/conda-forge/ipopt-feedstock/issues/53 .
Fix https://github.com/conda-forge/ipopt-feedstock/issues/57 .

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
At the CMake level, this includes the following changes: 
* https://github.com/traversaro/coinor-cmake/commit/66153ec362a75c220f4dc41c7bf17e2871da5e58
* https://github.com/traversaro/coinor-cmake/commit/2cabf53c332430b603af51b34122bc4d26d55ae1

However, given that the amount of changes to the CMake files continue to grow, probably the easiest strategy is jut to vendor the CMake scripts directly in the recipe. I can do this in the PR for fixing https://github.com/conda-forge/ipopt-feedstock/issues/56 .

**Comment by moorepants** [comment]
This looks fine. I don't know what the consequences of removing the chunk of CMAKE code, but it seems none for the purposes of this build.

**Comment by traversaro** [comment]
> 
> 
> This looks fine. I don't know what the consequences of removing the chunk of CMAKE code, but it seems none for the purposes of this build.

You are right, I should have deferred that change in another commit. The main change was just assuming that `std::finite`  is available (as it is available on the Windows platform targeted by conda-forge), and this remove the needs for all the `COIN_C_FINITE_R`/`COIN_C_FINITE` related logic. While I was at it, I noticed that `COIN_C_NAN` and `COIN_C_ISNAN` definitions were not used anywhere, so I removed that logic.

**Comment by moorepants** [comment]
Ok. I'll merge.

**Comment by moorepants** [comment]
> However, given that the amount of changes to the CMake files continue to grow, as already discussed in other issues (#51) probably the easiest strategy is jut to vendor the CMake scripts directly in the recipe. I can do this in the PR for providing the fix for #56 .

I think this probably the right move.

**Pull request merged**
